# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperacaoTitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('acao', models.CharField(choices=[('V', 'Venda'), ('R', 'Resgate')], max_length=7)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=19)),
                ('categoria_titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesouro_direto.CategoriaTitulo')),
            ],
        ),
    ]
