# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesouro_direto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacaotitulo',
            name='acao',
            field=models.CharField(choices=[('venda', 'Venda'), ('resgate', 'Resgate')], max_length=7),
        ),
    ]
