# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesouro_direto', '0002_auto_20170327_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='TituloTesouro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_titulo', models.CharField(choices=[('LTN', 'LTN'), ('LFT', 'LFT'), ('NTN-B', 'NTN-B'), ('NTN-B Principal', 'NTN-B Principal'), ('NTN-C', 'NTN-C'), ('NTN-F', 'NTN-F')], max_length=15)),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('acao', models.CharField(choices=[('venda', 'venda'), ('resgate', 'resgate')], max_length=7)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.RemoveField(
            model_name='operacaotitulo',
            name='categoria_titulo',
        ),
        migrations.DeleteModel(
            name='CategoriaTitulo',
        ),
        migrations.DeleteModel(
            name='OperacaoTitulo',
        ),
    ]
