# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tesouro_direto', '0003_auto_20170327_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacaoTitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('acao', models.CharField(choices=[('venda', 'venda'), ('resgate', 'resgate')], max_length=7)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.RemoveField(
            model_name='titulotesouro',
            name='acao',
        ),
        migrations.RemoveField(
            model_name='titulotesouro',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='titulotesouro',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='titulotesouro',
            name='valor',
        ),
        migrations.AddField(
            model_name='operacaotitulo',
            name='titulo_tesouro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesouro_direto.TituloTesouro'),
        ),
    ]
